import Head from 'next/head';
import Pokedex from '../components/Pokedex';
import LoginModal from '@/components/Auth/auth';
import { useState } from 'react';

export default function Home() {
  const [isModalOpen, setIsModalOpen] = useState<boolean>(false);

  return (
    <>
      <Head>
        <title>Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <button onClick={ () => {setIsModalOpen(true)}}>Sign In</button>
        {isModalOpen && (
          <LoginModal onClose={() => setIsModalOpen(false)}/>
        )}
        <h1>Pokedex dos cria</h1>
        <Pokedex />
      </main>
    </>
  );
}